django_forms_sandbox/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
]

main/urls.py
from django.urls import path
from .views import (
    IndexView,
    Example01,
    Example02,
    Example03
)

app_name = 'main'
urlpatterns = [
    path('', IndexView.as_view(), name='index'),
    path('example_01/', Example01.as_view(), name='example_01'),
    path('example_02/', Example02.as_view(), name='example_02'),
    path('example_03/', Example03.as_view(), name='example_03')
]

main/models.py
from django.db import models

# Create your models here.

main/forms.py
from django import forms
from django.forms import formset_factory

class ContactForm(forms.Form):
    subject = forms.CharField(max_length=100)
    message = forms.CharField(widget=forms.Textarea)
    sender = forms.EmailField()
    cc_myself = forms.BooleanField(required=False)

ContactFormSet = formset_factory(ContactForm, extra=2)

main/views.py
from django.shortcuts import render, redirect
from django.views import View
from django.urls import reverse

from .forms import ContactForm

class IndexView(View):
    def get(self, request):
        return render(request, 'main/index.html')

class Example01(View):
    """Using the Form class to render HTML forms in templates."""
    def get(self, request):
        contact_form = ContactForm()

        return render(request, 'main/example_01.html', {
            'contact_form': contact_form
        })

    def post(self, request):
        contact_form = ContactForm(request.POST)
        if contact_form.is_valid():
            sender = contact_form.cleaned_data['sender']
            cc_myself = contact_form.cleaned_data['cc_myself']

            recipients = ['info@example.com']

            if cc_myself:
                recipients.append(sender)

            context = {}
            request.session.update(contact_form.cleaned_data)
            request.session.update({ 'recipients': recipients })

            return redirect(reverse('main:index'))

class Example02(View):
    """Adding form fields manually."""
    def get(self, request):
        contact_form = ContactForm(label_suffix='')

        return render(request, 'main/example_02.html', {
            'contact_form': contact_form
        })

    def post(self, request):
        contact_form = ContactForm(request.POST)
        request.session.update({'is_last_form_submit_valid': contact_form.is_valid()})

        if contact_form.is_valid():
            request.session.update(contact_form.cleaned_data)

        return redirect(reverse('main:index'))

class Example03(View):
    def get(self, request):
        return render(request, 'main/example_03.html')

main/views/examples.py
from django.shortcuts import render, redirect
from django.views import View
from django.urls import reverse

from main.forms import ContactForm, ContactFormSet


class Example01(View):
    """Using the Form class to render HTML forms in templates."""
    def get(self, request):
        contact_form = ContactForm()

        return render(request, 'main/example_01.html', {
            'contact_form': contact_form
        })

    def post(self, request):
        contact_form = ContactForm(request.POST)
        if contact_form.is_valid():
            sender = contact_form.cleaned_data['sender']
            cc_myself = contact_form.cleaned_data['cc_myself']

            recipients = ['info@example.com']

            if cc_myself:
                recipients.append(sender)

            context = {}
            request.session.update(contact_form.cleaned_data)
            request.session.update({ 'recipients': recipients })

            return redirect(reverse('main:index'))


class Example02(View):
    """Adding form fields manually."""
    def get(self, request):
        contact_form = ContactForm(label_suffix='')

        return render(request, 'main/example_02.html', {
            'contact_form': contact_form
        })

    def post(self, request):
        contact_form = ContactForm(request.POST)
        request.session.update({'is_last_form_submit_valid': contact_form.is_valid()})

        if contact_form.is_valid():
            request.session.update(contact_form.cleaned_data)

        return redirect(reverse('main:index'))


class Example03(View):
    INITIAL_CONTACT_FORMSET_VALUES = [
        {
            'subject': 'The first contact form',
            'message': 'The first message. Weee!',
            'sender': 'lydia.night@example.com',
            'cc_myself': True
        }
    ]

    def get(self, request):
        formset = ContactFormSet(initial=INITIAL_CONTACT_FORMSET_VALUES)
        return render(request, 'main/example_03.html', {
            'formset': formset
        })


__all__ = ['Example01', 'Example02', 'Example03']

main/views/index.py
from django.shortcuts import render
from django.views import View

class IndexView(View):
    def get(self, request):
        return render(request, 'main/index.html')

__all__ = ['IndexView']

templates/base.html
<!DOCTYPE html>
<html>
<head>
    <title>
        {% block title %} Playing with Django Forms {% endblock %}
    </title>

    {% include 'partials/library_includes.html' %}
</head>
<body>
    {% include 'partials/navbar.html' %}

    <div class="container p-5">
        {% block content %}
        {% endblock %}
    </div>
</body>
</html>

templates/main/example_01.html
{% extends "base.html" %}

{% block title %} Example 1 {% endblock title %}

{% block content %}
    <h1 class="mb-3">A Primer on Django Forms</h1>

    <form action="" method="post">
        {% csrf_token %}
        {{ contact_form.as_p }}
        <input type="submit" value="Submit">
    </form>
{% endblock content %}

templates/main/example_02.html
{% extends "base.html" %}

{% block title %} Example 2 {% endblock title %}

{% block content %}
    <h1 class="mb-3">Rendering Form Fields Manually &mdash; Still Using Django Forms</h1>

    <form action="" method="post">
        {% csrf_token %}

        {{ contact_form.non_field_errors }}

        <p>
            {{ contact_form.subject.errors }}
            {{ contact_form.subject.label }} <br>
            {{ contact_form.subject.id_for_label }} <br>
            {{ contact_form.subject.help_text }} <br>
            {{ contact_form.subject.field }} <br>
            {{ contact_form.subject.label_tag }}
            {{ contact_form.subject }}
        </p>

        <p>
            {{ contact_form.message.errors }}
            {{ contact_form.message.label_tag }}
            {{ contact_form.message }}
        </p>

        <p>
            {{ contact_form.sender.errors }}
            {{ contact_form.sender.label_tag }}
            {{ contact_form.sender }}
        </p>

        <p>
            {{ contact_form.cc_myself.errors }}
            {{ contact_form.cc_myself.label_tag }}
            {{ contact_form.cc_myself }}
        </p>

        <input type="submit" value="Submit">
    </form>
{% endblock content %}

templates/main/example_03.html
{% extends "base.html" %}

{% block title %} Example 3 {% endblock title %}

{% block content %}
    <h1 class="mb-3">Formsets</h1>

    {% for form in formset %}
        <h2 class="my-3">Contact Form</h2>

        {% for field in form %}
            <div class="field-wrapper">
                {{ field.errors }}
                {{ field.label_tag }}
                {{ field }}
            </div>
        {% endfor %}
    {% endfor %}
{% endblock content %}

templates/main/index.html
{% extends "base.html" %}

{% block title %} Home {% endblock title %}

{% block content %}
    <h1 class="mb-3">Playing with Django Forms</h1>

    <p>Feel free to navigate for examples.</p>

    {% include 'partials/session_info.html' %}
{% endblock content %}

templates/partials/library_includes.html
<!-- Bootstrap 4 -->

<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

templates/partials/navbar.html
<nav class="navbar navbar-expand-lg navbar-dark bg-danger">
    <a class="navbar-brand" href="{% url 'main:index' %}">Navbar</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
            <li class="nav-item">
                <a class="nav-link" href="{% url 'main:example_01' %}">Example 1</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'main:example_02' %}">Example 2</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'main:example_03' %}">Example 3</a>
            </li>
        </ul>
    </div>
</nav>

templates/partials/session_info.html
<h2>Session Information</h2>

<ul>
{% for session_key, session_value in request.session.items %}
    <li>{{ session_key }} &mdash; {{ session_value }}</li>
{% endfor %}

    <li>request.session.session_key &mdash; {{ request.session.session_key }}</li>
    <li>request.session.session_data &mdash; {{ request.session.session_data }}</li>
</ul>